### ISSUE TITLE
flux is not pulling the newly built image

### ISSUE THREAD

**Issue by dtenenba** [github-developer/example-actions-flux-eks#2]
The system described in this repo worked for my first few commits, but then I needed to request more memory and CPU for my app because it was having an error related to running out of memory. I made the following change to `manifests/deployment.yml`:

Before:

```
...
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
```

After:

```
...
        resources:
            cpu: 500m
            memory: 1024M
          limits:
            cpu: 1000m
            memory: 2048M
```

Since my `build.yml` does not trigger on commits to the `manifests` directory, I also made a non-significant change (added a space to a line that was commented out) in a file outside that directory, to trigger GitHub Actions. 

My image was rebuilt and pushed but Flux did not pull the image and redeploy my pod. The Flux log ends as follows:

```
$ kubectl logs flux-6df96947dc-frrzt --namespace=flux
...
ts=2019-12-29T06:13:52.279663558Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: scanning multidoc from \"manifests/deployment.yml\": yaml: line 28: did not find expected key"
```

Line 28 is the line in the `resources` section saying `memory: 1024M`. I'm not sure which key is missing or expected. I added this request based on the documentation:

https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory

Any ideas?
